/*
 * PacketType.java
 * Author : 박찬형
 * Created Date : 2020-11-12
 */
package datatype.packet;

public enum PacketType{
    LOGIN, REQUEST_ROOM, RESPONSE_ROOM, MAKE_ROOM, REQUEST_USER, RESPONSE_USER, JOIN_ROOM, JOIN_ROOM_RESULT,
    READY, CHAT, START_REQUEST, DISCONNECT, QUIT_ROOM, START_GAME, START_ROUND, END_ROUND, DRAW, END_GAME
}